# .github/workflows/deploy-frontend.yml

name: Deploy LLM Detector Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'llm-detector/**'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./llm-detector

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NEW STEP: Create config.js from GitHub Secrets
      - name: Create config.js
        run: |
          echo "const API_BASE_URL = '${{ secrets.API_BASE_URL }}';" > config.js
          echo "const WAKEUP_LAMBDA_URL = '${{ secrets.WAKEUP_LAMBDA_URL }}';" >> config.js
          echo "--- config.js created successfully ---"
          cat config.js # This prints the file content to the log for debugging

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          # The sync command will now find and upload the dynamically created config.js
          aws s3 sync . s3://www.georgewallden.com/llm-detector --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2ZL7HX4ZYZ96R --paths "/llm-detector/*"